# Generated by Django 3.2.9 on 2021-12-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20211206_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
            preserve_default=False,
        ),
    ]
