# Generated by Django 3.2.9 on 2021-12-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_employee_details_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='designamtion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
